### ISSUE TITLE
In-app purchases: should we keep them in?

### ISSUE THREAD

**Issue by davidvanleeuwen** [awkward/beam#7]
Beam has been open source for a few months now. The first question [[1]](https://www.reddit.com/r/beamreddit/comments/7hp7ya/beam_the_open_source_reddit_client_for_ios/) we got was about the in-app purchases. 

Although it's unsure whether people want to help out continuing the development of Beam, there is something to say about the in-app purchases not making sense anymore... especially when there's a possibility that it's holding people back to help out.

But if we remove in-app purchases, how does it work with the functionality provided within the packs? Do we remove packs and add everything on by default? Or how would that work.

**Comment by renssies** [comment]
Personally, I would want to remove the in-app purchases and make all abilities with available by default because of 2 reasons:
- If people work on this app and work on or fix a feature that is behind an in-app purchase, we would be receiving the money for work others did.  
- Removing the code that is related to the in-app purchases would clean-up the app a lot.

**Comment by renssies** [comment]
We've decided to remove the in-app purchases for packs. From now on all packs are offered for free until we actually remove the in-app purchases from the app.
